<a href="https://colab.research.google.com/github/GuilhermePelegrina/Mackenzie/blob/main/Provas/Prova_N1_adult_turma_6O12_gabarito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://raw.githubusercontent.com/guilhermepelegrina/Mackenzie/main/logo_mackenzie.png'>

# **Prova N1 - Análise de Dados - Turma 6O12**

Este notebook contém as instruções e questões da Prova N1 para a disciplina de Análise de Dados da turma 6O12.

# Instruções

## Leitura dos dados

Para responder as questões da prova, utilize o conjunto de dados [Adult Income](https://archive.ics.uci.edu/dataset/2/adult). Essa base de dados contém os seguintes atributos descrevendo pessoas:

- `Age`: Idade.

- `Education`: Escolaridade.

- `Marital status`: Estado civil.

- `Occupation`: Profissão.

- `Race`: Raça.

- `Sex`: Sexo.

- `Capital-gain`: Ganho de capital vindo de investimentos.

- `Capital-loss`: Perda de capital em investimentos.

- `Hours-per-week`: Número de horas trabalhadas por semana.

- `Native-country`: País de nascimento.

Para cada pessoa, há também a indicação se esse indivíduo possui uma renda maior que 50 mil por ano ou no máximo esse valor. Isso é indicado pelo atributo `Income`.

Para ler o conjunto de dados, utilize o arquivo `.csv` disponível no link abaixo:

https://raw.githubusercontent.com/guilhermepelegrina/Mackenzie/main/Datasets/data_adult_income_modified.csv

## Questões e respostas

As questões se encontram logo ao final das instruções. Após cada questão, há células para inserirem códigos e buscarem pelas respostas (insira mais células, se necessário). Além disso, também há células de texto para que seja escrita a resposta da questão.

## Envio do notebook com as questões e respostas

Após finalizar a prova, faça o download do notebook no formato `.ipynb` e submeta no Moodle, da seguinte forma:

- Antes de salvar o arquivo, confira se todas as questões, seus códigos e suas respostas estão no notebook.

- Para fazer o download do notebook no formato `.ipynb`, clique em *Arquivo* - *Fazer download* - *Fazer o download do .ipynb*. Salve o arquivo com seu RA e nome (ex: 1172211_Guilherme).

- Após fazer o download do notebook, submeta o arquivo no Moodle. Para isso, acesse o Moodle, vá até o tópico *Provas* - *Envio da Prova N1* e envie o arquivo. **Lembre-se de finalizar o envio!**

# BOA PROVA!

**Questão 1 (0,5 pontos)** Leia o arquivo mencionado acima. Há quantas colunas e quantas linhas nessa base de dados?

*Escreva aqui sua resposta:*

30162 e 11

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

import pandas as pd
dados = pd.read_csv('https://raw.githubusercontent.com/guilhermepelegrina/Mackenzie/main/Datasets/data_adult_income_modified.csv', sep = ";")
dados

,Age,Education,Marital status,Occupation,Race,Sex,Capital-gain,Capital-loss,Hours-per-week,Native-country,Income
0,37,1st-4th,Married-civ-spouse,Craft-repair,Asian-Pac-Islander,Male,0,0,40,Cambodia,<=50K
1,25,Some-college,Never-married,Craft-repair,Asian-Pac-Islander,Female,0,0,40,Cambodia,<=50K
2,27,Some-college,Never-married,Craft-repair,Asian-Pac-Islander,Male,0,1876,45,Cambodia,<=50K
3,65,HS-grad,Never-married,Craft-repair,Asian-Pac-Islander,Male,0,0,40,Cambodia,<=50K
4,34,Bachelors,Never-married,Exec-managerial,Asian-Pac-Islander,Male,1471,0,40,Cambodia,<=50K
...,...,...,...,...,...,...,...,...,...,...,...
30157,29,Bachelors,Married-civ-spouse,Exec-managerial,White,Male,0,0,52,Yugoslavia,>50K
30158,35,Bachelors,Married-civ-spouse,Farming-fishing,White,Male,0,0,65,Yugoslavia,>50K
30159,66,Assoc-acdm,Married-civ-spouse,Machine-op-inspct,White,Male,5556,0,40,Yugoslavia,>50K
30160,35,HS-grad,Married-civ-spouse,Other-service,White,Male,0,0,40,Yugoslavia,>50K
30161,40,9th,Married-civ-spouse,Other-service,White,Female,0,0,40,Yugoslavia,>50K

**Questão 2 (0,5 pontos)** Há quantos estados civis nessa base de dados? Indique quais são eles.

*Escreva aqui sua resposta:*

7, 'Married-civ-spouse', 'Never-married', 'Divorced', 'Married-spouse-absent', 'Separated', 'Widowed', 'Married-AF-spouse'

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

dados['Marital status'].unique()

array(['Married-civ-spouse', 'Never-married', 'Divorced',
       'Married-spouse-absent', 'Separated', 'Widowed',
       'Married-AF-spouse'], dtype=object)

**Questão 3 (0,5 pontos)** Em relação ao sexto indivíduo dessa base de dados, quantos anos ele(a) tem?

*Escreva aqui sua resposta:*

32

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

dados.head(8)

,Age,Education,Marital status,Occupation,Race,Sex,Capital-gain,Capital-loss,Hours-per-week,Native-country,Income
0,37,1st-4th,Married-civ-spouse,Craft-repair,Asian-Pac-Islander,Male,0,0,40,Cambodia,<=50K
1,25,Some-college,Never-married,Craft-repair,Asian-Pac-Islander,Female,0,0,40,Cambodia,<=50K
2,27,Some-college,Never-married,Craft-repair,Asian-Pac-Islander,Male,0,1876,45,Cambodia,<=50K
3,65,HS-grad,Never-married,Craft-repair,Asian-Pac-Islander,Male,0,0,40,Cambodia,<=50K
4,34,Bachelors,Never-married,Exec-managerial,Asian-Pac-Islander,Male,1471,0,40,Cambodia,<=50K
5,32,Preschool,Married-civ-spouse,Machine-op-inspct,Asian-Pac-Islander,Female,4508,0,40,Cambodia,<=50K
6,28,HS-grad,Never-married,Machine-op-inspct,Asian-Pac-Islander,Male,0,0,40,Cambodia,<=50K
7,35,HS-grad,Never-married,Machine-op-inspct,Asian-Pac-Islander,Male,0,0,40,Cambodia,<=50K

**Questão 4 (0,5 pontos)** Qual o primeiro quartil do atributo que indica a idade? Lembre-se que, nesse caso, o primeiro quartil vai indicar a idade que pelo menos 75% dos indivíduos possuem.

*Escreva aqui sua resposta:*

28

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

dados['Age'].describe()

count    30162.000000
mean        38.437902
std         13.134665
min         17.000000
25%         28.000000
50%         37.000000
75%         47.000000
max         90.000000
Name: Age, dtype: float64

**Questão 5 (0,5 pontos)** Qual o percentual de indivíduos divorciados (categoria *Divorced*) nessa base de dados?

*Escreva aqui sua resposta:*

13,97%

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

dados['Marital status'].value_counts()['Divorced']/len(dados)

0.13971222067502154

**Questão 6 (0,5 pontos)** Qual o percentual de indivíduos com pelo menos 35 anos nessa base de dados?

*Escreva aqui sua resposta:*

57,19%

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

len(dados[dados.Age >= 35])/len(dados)

0.5719779855447251

**Questão 7 (1,0 ponto)** Para os homens (*Male*) com menos de 65 anos, quantos recebem mais de 50 mil por ano?

*Escreva aqui sua resposta:*

6197

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

len(dados[(dados.Sex == 'Male') & (dados['Age'] < 65) & (dados['Income'] == '>50K')])

6197

**Questão 8 (1,0 ponto)** Dentre as mulheres (*Female*), qual porcentagem recebem no máximo 50 mil por ano?

*Escreva aqui sua resposta:*

88,63%

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

len(dados[(dados.Sex == 'Female') & (dados['Income'] == "<=50K")])/len(dados[dados.Sex == 'Female'])

0.8863218155796361

**Questão 9 (1,0 ponto)** Ao comparar os homens e mulheres nessa base de dados e levando em conta apenas os indivíduos que ganham mais do que 50 mil por ano, a pessoa que teve a maior perda de capital com investimentos é um homem ou uma mulher? Qual a idade dessa pessoa?

*Escreva aqui sua resposta:*

Mulher, 74

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

maximo = dados[dados["Income"] == ">50K"]["Capital-loss"].max()
print(maximo)

dados2 = dados[dados["Capital-loss"] == maximo]
dados2

3683

,Age,Education,Marital status,Occupation,Race,Sex,Capital-gain,Capital-loss,Hours-per-week,Native-country,Income
17380,68,HS-grad,Divorced,Prof-specialty,White,Female,0,3683,40,United-States,<=50K
27427,74,Doctorate,Never-married,Prof-specialty,White,Female,0,3683,20,United-States,>50K

**Questão 10 (1,0 ponto)** Muitas vezes, essa base de dados é utilizada para ilustrar um cenário de disparidade entre homens e mulheres. Verifique a porcentagem dos homens e das mulheres que ganham mais de 50 mil por ano. A disparidade é grande? Considere que uma diferença maior que 10% indica uma disparidade grande. Justifique sua resposta com base nas porcentagens calculadas.

*Escreva aqui sua resposta:*

Mulheres: 11,36% (1112/9782)

Homens: 31,38% (6396/20380)

Disparidade grande.

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

dados.groupby(["Sex","Income"]).count()

                 Age  Education  Marital status  Occupation   Race  \
Sex    Income
Female <=50K    8670       8670            8670        8670   8670
       >50K     1112       1112            1112        1112   1112
Male   <=50K   13984      13984           13984       13984  13984
       >50K     6396       6396            6396        6396   6396

               Capital-gain  Capital-loss  Hours-per-week  Native-country
Sex    Income
Female <=50K           8670          8670            8670            8670
       >50K            1112          1112            1112            1112
Male   <=50K          13984         13984           13984           13984
       >50K            6396          6396            6396            6396

In [ ]:
# Outra forma

Porcentagem_Homens = len(dados[(dados['Sex'] == 'Male') & (dados['Income'] == '>50K')]) / len(dados[dados['Sex'] == 'Male'])
Porcentagem_Mulheres = len(dados[(dados['Sex'] == 'Female') & (dados['Income'] == '>50K')]) / len(dados[dados['Sex'] == 'Female'])

print('Porcentagem Homens:', Porcentagem_Homens)
print('Porcentagem Mulheres:', Porcentagem_Mulheres)

Diferença = abs(Porcentagem_Homens - Porcentagem_Mulheres)

Porcentagem Homens: 0.3138370951913641
Porcentagem Mulheres: 0.11367818442036394

**Questão 11 (1,0 ponto)** Verifique, agora, se há disparidades em relação aos brancos (categoria *White*) e negros (categoria *Black*). Para os brancos e para os negros, verifique a porcentagem dos que ganham mais que 50 mil por ano. A disparidade é grande? Considere, também, que uma diferença maior que 10% indica uma disparidade grande. Justifique sua resposta com base nas porcentagens calculadas.

*Escreva aqui sua resposta:*

Brancos: 26,37% (6839/25933)

Negros: 12,99% (366/2817)

Disparidade é grande.

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

dados.groupby(["Race","Income"]).count()

                             Age  Education  Marital status  Occupation  \
Race               Income
Amer-Indian-Eskimo <=50K     252        252             252         252
                   >50K       34         34              34          34
Asian-Pac-Islander <=50K     647        647             647         647
                   >50K      248        248             248         248
Black              <=50K    2451       2451            2451        2451
                   >50K      366        366             366         366
Other              <=50K     210        210             210         210
                   >50K       21         21              21          21
White              <=50K   19094      19094           19094       19094
                   >50K     6839       6839            6839        6839

                             Sex  Capital-gain  Capital-loss  Hours-per-week  \
Race               Income
Amer-Indian-Eskimo <=50K     252           252           252             252
                   >50K       34            34            34              34
Asian-Pac-Islander <=50K     647           647           647             647
                   >50K      248           248           248             248
Black              <=50K    2451          2451          2451            2451
                   >50K      366           366           366             366
Other              <=50K     210           210           210             210
                   >50K       21            21            21              21
White              <=50K   19094         19094         19094           19094
                   >50K     6839          6839          6839            6839

                           Native-country
Race               Income
Amer-Indian-Eskimo <=50K              252
                   >50K                34
Asian-Pac-Islander <=50K              647
                   >50K               248
Black              <=50K             2451
                   >50K               366
Other              <=50K              210
                   >50K                21
White              <=50K            19094
                   >50K              6839

**Questão 12 (1,0 ponto)** Indique o estado civil e o sexo da pessoa que teve a maior perda de capital nos investimentos. Apresente também essa perda de capital máxima. Não precisa traduzir para o português.

*Escreva aqui sua resposta:*

Mulher, Widowed. Perda de capital de 4356

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

dados.groupby(['Marital status','Sex']).max()

                              Age     Education        Occupation   Race  \
Marital status        Sex
Divorced              Female   90  Some-college  Transport-moving  White
                      Male     83  Some-college  Transport-moving  White
Married-AF-spouse     Female   43  Some-college             Sales  White
                      Male     47  Some-college  Transport-moving  White
Married-civ-spouse    Female   90  Some-college  Transport-moving  White
                      Male     90  Some-college  Transport-moving  White
Married-spouse-absent Female   80  Some-college  Transport-moving  White
                      Male     79  Some-college  Transport-moving  White
Never-married         Female   90  Some-college  Transport-moving  White
                      Male     90  Some-college  Transport-moving  White
Separated             Female   90  Some-college  Transport-moving  White
                      Male     74  Some-college  Transport-moving  White
Widowed               Female   90  Some-college  Transport-moving  White
                      Male     90  Some-college  Transport-moving  White

                              Capital-gain  Capital-loss  Hours-per-week  \
Marital status        Sex
Divorced              Female         99999          3900              99
                      Male           99999          2824              99
Married-AF-spouse     Female             0             0              42
                      Male            7298             0              90
Married-civ-spouse    Female         99999          2415              99
                      Male           99999          2603              99
Married-spouse-absent Female         27828          2472              90
                      Male           99999          1980              99
Never-married         Female         99999          3683              99
                      Male           99999          2824              99
Separated             Female         99999          3900              90
                      Male           99999          3770              99
Widowed               Female         99999          4356              99
                      Male           25124          2392              99

                             Native-country Income
Marital status        Sex
Divorced              Female     Yugoslavia   >50K
                      Male          Vietnam   >50K
Married-AF-spouse     Female  United-States   >50K
                      Male    United-States   >50K
Married-civ-spouse    Female     Yugoslavia   >50K
                      Male       Yugoslavia   >50K
Married-spouse-absent Female        Vietnam   >50K
                      Male    United-States   >50K
Never-married         Female     Yugoslavia   >50K
                      Male       Yugoslavia   >50K
Separated             Female  United-States   >50K
                      Male    United-States   >50K
Widowed               Female  United-States   >50K
                      Male    United-States   >50K

In [ ]:
# Outra forma

print(dados[dados['Capital-loss'] == dados['Capital-loss'].max()])

      Age Education Marital status       Occupation   Race     Sex  \
8746   82   HS-grad        Widowed  Exec-managerial  White  Female

      Capital-gain  Capital-loss  Hours-per-week Native-country Income  saldo
8746             0          4356              18  United-States  <=50K  -4356

**Questão 13 (1,0 ponto)** Crie uma nova coluna de dados (dê o nome que quiser) que indique, para cada indivíduo, o saldo dos investimentos. Ou seja, a diferença entre o ganho e perda de capital nos investimentos. Calcule a média e o desvio-padrão dessa nova coluna de dados.

*Escreva aqui sua resposta:*

Média: 1003.63

Desvio-padrão: 7430.37

In [ ]:
# Escreva aqui seus códigos (insira mais células, se necessário)

dados['saldo'] = dados['Capital-gain'] - dados['Capital-loss']
print(dados['saldo'].mean(), dados['saldo'].std())

1003.6353690073603 7430.372729839309